[aliyun]
user_tag = "lichenxing-alpha-3"
image_name = "conflux-docker-base"
ssh_key_path = "./keys/ssh-key.pem"

[[aliyun.regions]]
name = "ap-southeast-5"
count = 3

[[aliyun.regions]]
name = "ap-southeast-3"
count = 3

[[aliyun.regions]]
name = "ap-southeast-6"
count = 3

[[aliyun.regions]]
name = "ap-southeast-7"
count = 3

[[aliyun.regions]]
name = "ap-northeast-2"
count = 3

[[aliyun.regions]]
name = "ap-southeast-1"
count = 3

[[aliyun.regions]]
name = "me-east-1"
count = 3

[[aliyun.instance_types]]
name = "ecs.g8i.2xlarge"
nodes = 1

[[aliyun.instance_types]]
name = "ecs.g9i.2xlarge"
nodes = 1

[[aliyun.instance_types]]
name = "ecs.g7.2xlarge"
nodes = 1