[aliyun]
# 云服务固有配置需要，不可修改
provider = "aliyun"
default_user_name = "root"

# 以下可修改
user_tag = "lichenxing-alpha-5"
image_name = "conflux-docker-base"
ssh_key_path = "./keys/ssh-key.pem"

[[aliyun.regions]]
name = "ap-southeast-5"
count = 3

[[aliyun.regions]]
name = "ap-southeast-3"
count = 3

[[aliyun.regions]]
name = "ap-southeast-6"
count = 3

[[aliyun.regions]]
name = "ap-southeast-7"
count = 3

[[aliyun.regions]]
name = "ap-northeast-2"
count = 3

[[aliyun.regions]]
name = "ap-southeast-1"
count = 3

[[aliyun.regions]]
name = "me-east-1"
count = 3

[[aliyun.instance_types]]
name = "ecs.g8i.2xlarge"
nodes = 1

[[aliyun.instance_types]]
name = "ecs.g9i.2xlarge"
nodes = 1

[[aliyun.instance_types]]
name = "ecs.g7.2xlarge"
nodes = 1

[aws]
# 云服务固有配置需要，不可修改
provider = "aws"
default_user_name = "ubuntu"

# 以下可修改
user_tag = "lichenxing-alpha-1"
image_name = "massive-test-seed"
ssh_key_path = "./keys/ssh-key.pem"

[[aws.regions]]
name = "us-west-2"
count = 3

[[aws.instance_types]]
name = "m6i.2xlarge"
nodes = 1

[tencent]
# 云服务固有配置需要，不可修改
provider = "tencent"
default_user_name = "ubuntu"

# 以下可修改
user_tag = "lichenxing-alpha-5"
image_name = "conflux-docker-base"
ssh_key_path = "./keys/ssh-key.pem"

[[tencent.instance_types]]
name = "S8.2XLARGE32"
nodes = 1

[[tencent.instance_types]]
name = "SA9.2XLARGE32"
nodes = 1

[[tencent.instance_types]]
name = "S9.2XLARGE32"
nodes = 1